spring:
  datasource:
    username: jacksie
    password: 123
    url: jdbc:mysql://localhost:3306/hotel?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 9090
mybatis:
  type-aliases-package: com.web.hotel.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml

